exp_name: 'train_given_anchors'
data: datasets
train_data_prefix: protac_1600 # train_all
val_data_prefix: protac_1600 # val_all
checkpoints: models
logs: logs
device: gpu
log_iterations: null
wandb_entity: null
enable_progress_bar: True

model: egnn_dynamics
lr: 2.0e-5 # 2.0e-4
batch_size: 4 # 64
n_layers: 8
n_epochs: 1000
test_epochs: 20
n_stability_samples: 10
nf: 128
activation: silu
attention: False
condition_time: True
tanh: False
norm_constant: 0.000001
inv_sublayers: 2
include_charges: False
diffusion_loss_type: l2
data_augmentation: False
center_of_mass: anchors

remove_anchors_context: False # True
sin_embedding: False
normalization_factor: 100
normalize_factors: [1, 4, 10]
aggregation_method: 'sum'
normalization: batch_norm

resume:
